title: "DiffPS: Leveraging Prior Knowledge of Diffusion Model for Person Search"
description: "ICCV 2025 Highlight Paper - DiffPS"

# GitHub Pages settings
baseurl: "/DiffPS"
url: "https://perceptualai-lab.github.io"

# Disable Jekyll processing for HTML files
plugins: []

# Include HTML files
include:
  - "*.html"

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore

# Allow HTML processing
markdown: kramdown
highlighter: rouge 